"""initial_schema_v2_1

Revision ID: b56166089a76
Revises: 
Create Date: 2026-03-24 01:08:32.320179+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56166089a76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_name', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=True),
    sa.Column('pattern_logic', sa.JSON(), nullable=True),
    sa.Column('applicability_conditions', sa.JSON(), nullable=True),
    sa.Column('severity_weight', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('contributed_by_node', sa.String(length=100), nullable=True),
    sa.Column('validated_by_nodes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_name', sa.String(length=255), nullable=False),
    sa.Column('indication_category', sa.String(length=100), nullable=True),
    sa.Column('evidence_structure', sa.JSON(), nullable=True),
    sa.Column('regulatory_outcome', sa.String(length=100), nullable=True),
    sa.Column('regulatory_agency', sa.String(length=100), nullable=True),
    sa.Column('approval_likelihood', sa.Float(), nullable=True),
    sa.Column('precedent_strength', sa.Float(), nullable=True),
    sa.Column('key_success_factors', sa.JSON(), nullable=True),
    sa.Column('critical_evidence_types', sa.JSON(), nullable=True),
    sa.Column('common_pitfalls', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source_submission_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('federated_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_url', sa.String(length=1000), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('available_data_types', sa.JSON(), nullable=True),
    sa.Column('supported_queries', sa.JSON(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('required_reviewers', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'ANALYST', 'VIEWER', name='userrole', native_enum=False), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('expertise_areas', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_organization', 'users', ['organization_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('notification_type', sa.String(length=100), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'REVIEW', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('research_intent', sa.Text(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('max_pubmed_results', sa.Integer(), nullable=True),
    sa.Column('max_trials_results', sa.Integer(), nullable=True),
    sa.Column('processing_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('idx_projects_created_by', 'projects', ['created_by'], unique=False)
    op.create_index('idx_projects_organization', 'projects', ['organization_id'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('alert_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_session_tokens_expires', 'session_tokens', ['expires_at'], unique=False)
    op.create_index('idx_session_tokens_hash', 'session_tokens', ['token_hash'], unique=False)
    op.create_index('idx_session_tokens_user', 'session_tokens', ['user_id'], unique=False)
    op.create_table('user_presence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('activity', sa.String(length=100), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('cursor_position', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adam_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_name', sa.String(length=50), nullable=False),
    sa.Column('dataset_label', sa.String(length=200), nullable=True),
    sa.Column('structure', sa.String(length=100), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('data_content', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adam_datasets_name', 'adam_datasets', ['dataset_name'], unique=False)
    op.create_index('idx_adam_datasets_project', 'adam_datasets', ['project_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('regulatory_significance', sa.Boolean(), nullable=True),
    sa.Column('retention_period_years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_project', 'audit_logs', ['project_id'], unique=False)
    op.create_index('idx_audit_logs_regulatory', 'audit_logs', ['regulatory_significance'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('evidence_critiques',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('overall_assessment', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('regulatory_concerns', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('alternative_approaches', sa.Text(), nullable=True),
    sa.Column('additional_evidence_needed', sa.JSON(), nullable=True),
    sa.Column('fda_acceptance_likelihood', sa.Float(), nullable=True),
    sa.Column('regulatory_precedents', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('critique_model', sa.String(length=100), nullable=True),
    sa.Column('reviewer_persona', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.Enum('PUBMED', 'CLINICALTRIALS', 'UPLOADED_DOCUMENT', 'INSTITUTIONAL_DATA', 'FEDERATED_SOURCE', name='evidencesourcetype', native_enum=False), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('query_used', sa.Text(), nullable=True),
    sa.Column('retrieval_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_type', 'source_id', name='uq_evidence_project_source')
    )
    op.create_index('idx_evidence_records_project', 'evidence_records', ['project_id'], unique=False)
    op.create_index('idx_evidence_records_source', 'evidence_records', ['source_type', 'source_id'], unique=False)
    op.create_table('parsed_specifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('indication', sa.String(length=255), nullable=True),
    sa.Column('population_definition', sa.Text(), nullable=True),
    sa.Column('primary_endpoint', sa.Text(), nullable=True),
    sa.Column('secondary_endpoints', sa.JSON(), nullable=True),
    sa.Column('inclusion_criteria', sa.JSON(), nullable=True),
    sa.Column('exclusion_criteria', sa.JSON(), nullable=True),
    sa.Column('follow_up_period', sa.String(length=100), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('statistical_plan', sa.Text(), nullable=True),
    sa.Column('covariates', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('clarifications', sa.JSON(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsing_model', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('template_version', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(length=36), nullable=True),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('regulatory_agency', sa.String(length=100), nullable=True),
    sa.Column('submission_context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regulatory_artifacts_project', 'regulatory_artifacts', ['project_id'], unique=False)
    op.create_index('idx_regulatory_artifacts_type', 'regulatory_artifacts', ['artifact_type'], unique=False)
    op.create_table('citation_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('citing_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('cited_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('citation_context', sa.Text(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cited_evidence_id'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['citing_evidence_id'], ['evidence_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparability_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_record_id', sa.String(length=36), nullable=True),
    sa.Column('population_similarity', sa.Float(), nullable=True),
    sa.Column('endpoint_alignment', sa.Float(), nullable=True),
    sa.Column('covariate_coverage', sa.Float(), nullable=True),
    sa.Column('temporal_alignment', sa.Float(), nullable=True),
    sa.Column('evidence_quality', sa.Float(), nullable=True),
    sa.Column('provenance_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('regulatory_viability', sa.Float(), nullable=True),
    sa.Column('dimension_details', sa.JSON(), nullable=True),
    sa.Column('scoring_rationale', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('scoring_model', sa.String(length=100), nullable=True),
    sa.Column('scoring_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['evidence_record_id'], ['evidence_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('text_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['review_comments.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_record_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.Enum('ACCEPTED', 'REJECTED', 'DEFERRED', 'PENDING', name='reviewdecisionenum', native_enum=False), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_criteria', sa.JSON(), nullable=True),
    sa.Column('alternative_considerations', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('review_duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_record_id'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'evidence_record_id', 'reviewer_id', name='uq_review_decision')
    )
    op.create_index('idx_review_decisions_project', 'review_decisions', ['project_id'], unique=False)
    op.create_index('idx_review_decisions_reviewer', 'review_decisions', ['reviewer_id'], unique=False)
    op.create_table('bias_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comparability_score_id', sa.String(length=36), nullable=True),
    sa.Column('bias_type', sa.Enum('SELECTION_BIAS', 'CONFOUNDING', 'MEASUREMENT_BIAS', 'TEMPORAL_BIAS', 'PUBLICATION_BIAS', name='biastype', native_enum=False), nullable=True),
    sa.Column('bias_severity', sa.Float(), nullable=True),
    sa.Column('bias_description', sa.Text(), nullable=True),
    sa.Column('fragility_score', sa.Float(), nullable=True),
    sa.Column('sensitivity_flags', sa.JSON(), nullable=True),
    sa.Column('regulatory_risk', sa.Float(), nullable=True),
    sa.Column('mitigation_strategies', sa.JSON(), nullable=True),
    sa.Column('adjustment_recommendations', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_model', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['comparability_score_id'], ['comparability_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bias_analyses')
    op.drop_index('idx_review_decisions_reviewer', table_name='review_decisions')
    op.drop_index('idx_review_decisions_project', table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_table('review_comments')
    op.drop_table('review_assignments')
    op.drop_table('evidence_embeddings')
    op.drop_table('comparability_scores')
    op.drop_table('citation_relationships')
    op.drop_index('idx_regulatory_artifacts_type', table_name='regulatory_artifacts')
    op.drop_index('idx_regulatory_artifacts_project', table_name='regulatory_artifacts')
    op.drop_table('regulatory_artifacts')
    op.drop_table('parsed_specifications')
    op.drop_index('idx_evidence_records_source', table_name='evidence_records')
    op.drop_index('idx_evidence_records_project', table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_table('evidence_critiques')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_regulatory', table_name='audit_logs')
    op.drop_index('idx_audit_logs_project', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_adam_datasets_project', table_name='adam_datasets')
    op.drop_index('idx_adam_datasets_name', table_name='adam_datasets')
    op.drop_table('adam_datasets')
    op.drop_table('user_presence')
    op.drop_index('idx_session_tokens_user', table_name='session_tokens')
    op.drop_index('idx_session_tokens_hash', table_name='session_tokens')
    op.drop_index('idx_session_tokens_expires', table_name='session_tokens')
    op.drop_table('session_tokens')
    op.drop_table('saved_searches')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_organization', table_name='projects')
    op.drop_index('idx_projects_created_by', table_name='projects')
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_table('notification_settings')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_organization', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('workflow_steps')
    op.drop_table('organizations')
    op.drop_table('federated_nodes')
    op.drop_table('evidence_patterns')
    op.drop_table('constraint_patterns')
    # ### end Alembic commands ###
